// GENERATED by build_production_catalog.py. Do not edit manually.
export const CATALOG_APPLICATION_ID = 1263027011;
export const CATALOG_USER_VERSION = 1;
export const CATALOG_IMAGE_SIZE = 200;
export const CATALOG_IMAGE_KEYS: Readonly<Record<number, string>> = {"1":"front_de","2":"front_fr","3":"front_en","4":"front_it","5":"front_es","6":"front_nl","7":"front_pl","8":"front_sv","9":"front_cs","10":"front_ru","11":"front_ro","12":"front_da","13":"front_hu","14":"front_pt","15":"front_bg","16":"front_hr","17":"front_nb","18":"front_fi","19":"front_tr","20":"front_ar","21":"front_no","22":"front_uk","23":"front_se","24":"front_xx","25":"front_sl","26":"front_el","27":"front_lb","28":"front_sk","29":"front_lt","30":"front_ja","31":"front_et","32":"front_sr","33":"front_ca","34":"front_zh","35":"front_id","36":"front_la","37":"front_af","38":"front_ch","39":"front_fy","40":"front_fa","41":"front_lv","42":"front_aa","43":"front_is","44":"front_th","45":"front_vi","46":"front_eu","47":"front_bs","48":"front_co","49":"front_cy","50":"front_jv","51":"front_ko","52":"front_gd","53":"front_gl","54":"front_ka","55":"front_mg","56":"front_az","57":"front_ht","58":"front_mt","59":"front_new_lc","60":"front_ny","61":"front_sq","62":"front_am","63":"front_be","64":"front_bn","65":"front_eo","66":"front_ha","67":"front_hy","68":"front_ms","69":"front_sn","70":"front_st","71":"front_tg","72":"front_uz"};
export const CATALOG_UNIT_KINDS = {"none":0,"mass":1,"volume":2,"portion":3,"piece":4,"bar":5,"slice":6,"package":7} as const;

export const CATALOG_SEARCH_SQL = `
SELECT p.id,p.g,p.n,d.v AS brand,p.c,p.s,p.q,p.u,p.m,p.r
FROM x
JOIN p ON p.id=x.rowid
LEFT JOIN d ON d.id=p.b
WHERE x MATCH ?
ORDER BY
  CASE
    WHEN lower(p.n)=lower(?) THEN 0
    WHEN lower(p.n) LIKE lower(?) || '%' THEN 1
    WHEN lower(p.n) LIKE '%' || lower(?) || '%' THEN 2
    ELSE 3
  END,
  p.r DESC,p.n COLLATE NOCASE ASC,p.id ASC
LIMIT ?`;

export const CATALOG_RESCUE_BARCODE_SQL = `
SELECT p.id,p.g,p.n,d.v AS brand,p.c,p.s,p.q,p.u,p.m,p.r
FROM p LEFT JOIN d ON d.id=p.b
WHERE p.g=? LIMIT 1`;

const IMAGE_SHIFT = 19;
const IMAGE_KEY_BITS = 7;
const IMAGE_KEY_MASK = 2 ** IMAGE_KEY_BITS - 1;
const OFF_IMAGE_BASE = "https://images.openfoodfacts.org/images/products";

export function packStandardGtin(code: string): number | null {
  if (!/^\d+$/.test(code)) return null;
  const lengthCode = code.length === 8 ? 0 : code.length === 13 ? 1 : code.length === 14 ? 2 : null;
  if (lengthCode === null) return null;
  const numeric = Number(code);
  if (!Number.isSafeInteger(numeric)) return null;
  return numeric * 4 + lengthCode + 1;
}

export function decodeCatalogCode(id: number, rescueCode: string | null): string {
  if (rescueCode) return rescueCode;
  const packed = id - 1;
  const lengthCode = packed % 4;
  const numeric = Math.floor(packed / 4);
  const width = lengthCode === 0 ? 8 : lengthCode === 1 ? 13 : lengthCode === 2 ? 14 : null;
  if (width === null) throw new Error('Ungültiger gepackter GTIN-Längencode');
  return String(numeric).padStart(width, '0');
}

function field(metadata: number, fromBit: number, width = 1): number {
  return Math.floor(metadata / 2 ** fromBit) % 2 ** width;
}

export function decodeCatalogMetadata(metadata: number) {
  if (!Number.isSafeInteger(metadata) || metadata < 0) throw new Error('Ungültige Katalogmetadaten');
  const imagePayload = Math.floor(metadata / 2 ** IMAGE_SHIFT);
  const flags = metadata % 2 ** IMAGE_SHIFT;
  const imageRef = imagePayload === 0 ? null : imagePayload - 1;
  return {
    carbohydrateBasisVolume: field(flags, 0) === 1,
    carbohydrateSourcePrepared: field(flags, 1) === 1,
    hasServing: field(flags, 2) === 1,
    servingBasisVolume: field(flags, 3) === 1,
    hasProductQuantity: field(flags, 4) === 1,
    productQuantityBasisVolume: field(flags, 5) === 1,
    standardGtin: field(flags, 6) === 1,
    gtinChecksumValid: field(flags, 7) === 1,
    hasQualityErrors: field(flags, 8) === 1,
    defaultUnitKind: field(flags, 9, 3),
    provenUnitKind: field(flags, 12, 3),
    provenUnitSource: field(flags, 15, 2),
    provenUnitBasisVolume: field(flags, 17) === 1,
    imageKeyId: imageRef === null ? null : imageRef % 2 ** IMAGE_KEY_BITS,
    imageRevision: imageRef === null ? null : Math.floor(imageRef / 2 ** IMAGE_KEY_BITS)
  };
}

function offImageProductPath(code: string): string {
  if (code.length <= 8) return code;
  return [code.slice(0, 3), code.slice(3, 6), code.slice(6, 9), code.slice(9)].join('/');
}

export function buildCatalogImageUrl(code: string, metadata: number): string | null {
  const decoded = decodeCatalogMetadata(metadata);
  if (decoded.imageKeyId === null || decoded.imageRevision === null) return null;
  const key = CATALOG_IMAGE_KEYS[decoded.imageKeyId];
  if (!key) return null;
  return `${OFF_IMAGE_BASE}/${offImageProductPath(code)}/${key}.${decoded.imageRevision}.${CATALOG_IMAGE_SIZE}.jpg`;
}

export function buildCatalogFtsQuery(input: string): string | null {
  const tokens = input.toLocaleLowerCase('de-DE').match(/[0-9a-zÀ-ÖØ-öø-ÿ]+/g)?.filter(token => token.length >= 2) ?? [];
  if (tokens.length === 0) return null;
  return tokens.map(token => `"${token.replaceAll('"', '""')}"*`).join(' AND ');
}
